// Auto-generated by @electron-ipc-controller/vite-plugin
// Do not edit manually

export type ComplexPayload = {
  id: string
  count?: number
  nested: NestedPayload
  tags: string[]
  union: string | number
}

export type NestedPayload = {
  flag: boolean
  kind: PayloadKind
}

export enum PayloadKind {
  A = 'a',
  B = 'b',
  C = 'c'
}

export type SimplePayload = {
  message: string
}

export interface IpcApi {
  counter: {
    get(): Promise<number>
    inc(by?: number): Promise<number>
    ping(): Promise<string>
    reset(): void
  }
  echo: {
    complex(input: ComplexPayload): Promise<ComplexPayload>
    fireAndForget(msg: string): void
    onceInvoke(msg: string): Promise<string>
    onceListen(): void
    simple(input: SimplePayload): Promise<SimplePayload>
  }
  util: {
    withOrigin(): Promise<{ hasFrame: boolean }>
    withRawEvent(): Promise<{ eventType: string }>
  }
}
