// Auto-generated by @electron-ipc-controller/vite-plugin
// Do not edit manually

export type ComplexInput = {
  key: string
  key2: NestedInput
}

export type NestedInput = {
  key: boolean
  key2: TestingEnum
}

export enum TestingEnum {
  ONE = 'one',
  TWO = 'two',
  THREE = 'three'
}

export interface IpcApi {
  counter: {
    complexExample(input: ComplexInput): Promise<ComplexInput>
    get(): Promise<number>
    inc(incrementBy?: number): Promise<number>
    ping(): Promise<string>
    reset(): void
  }
}

declare global {
  interface Window {
    ipc: IpcApi
  }
}

export {}
