// Auto-generated by @electron-ipc-controller/vite-plugin
// Do not edit manually

export interface IpcApi {
  counter: {
    get(): Promise<number>
    inc(incrementBy?: number): Promise<number>
    ping(): Promise<string>
    reset(): void
  }
}

declare global {
  interface Window {
    ipc: IpcApi
  }
}

export {}
