import { IPC_DEFAULT_API_ROOT } from "@electron-ipc-controller/shared";

import { ControllerMetadata } from "../parser/types.js";

import { getReturnType } from "./get-return-type.js";

export const generateTypes = (controllers: ControllerMetadata[], namespace: string = IPC_DEFAULT_API_ROOT): string => {
  const referencedTypes = new Map<string, string>();

  const collectTypes = (types: (typeof controllers)[0]["referencedTypes"]) => {
    types.forEach((t) => {
      if (t.definition && !referencedTypes.has(t.name)) {
        referencedTypes.set(t.name, t.definition);
        collectTypes(t.referencedTypes);
      }
    });
  };

  controllers.forEach((c) => collectTypes(c.referencedTypes));

  const typeDefinitions = Array.from(referencedTypes.entries())
    .sort((a, b) => a[0].localeCompare(b[0]))
    .filter(([, def]) => def.trim().length > 0)
    .map(([, def]) => `export ${def}`)
    .join("\n\n");

  const namespaces = controllers.map((controller) => {
    const methods = controller.methods.map((method) => {
      const params = method.params.map((p) => `${p.name}${p.optional ? "?" : ""}: ${p.type}`).join(", ");
      const returnType = getReturnType(method.decoratorName, method.returnType);
      return `${method.name}(${params}): ${returnType};`;
    });

    return `    ${controller.namespace}: {\n      ${methods.join("\n      ")}\n    };`;
  });

  const isValidIdentifier = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(namespace);
  const windowProperty = isValidIdentifier ? `${namespace}: IpcApi;` : `[${JSON.stringify(namespace)}]: IpcApi;`;

  return `// Auto-generated by @electron-ipc-controller/vite-plugin
// Do not edit manually

${typeDefinitions}

export interface IpcApi {
${namespaces.join("\n")}
}

declare global {
  interface Window {
    ${windowProperty}
  }
}

export {};
`;
};
