import { IPC_DEFAULT_API_ROOT } from "@electron-ipc-bridge/shared";

import { generateGlobalTypes } from "./generate-global-types.js";

describe("generateGlobalTypes", () => {
  it("uses IPC_DEFAULT_API_ROOT by default and emits import and window augmentation", () => {
    const code = generateGlobalTypes(undefined, "./ipc.types");

    expect(code).toContain("// Auto-generated by @electron-ipc-bridge/vite-plugin");
    expect(code).toContain(`import type { IpcApi } from "./ipc.types";`);
    expect(code).toContain("declare global {");
    expect(code).toContain("interface Window {");
    expect(code).toContain(`${IPC_DEFAULT_API_ROOT}: IpcApi;`);
  });

  it("emits a computed property when namespace is not a valid identifier", () => {
    const code = generateGlobalTypes("custom-api-root", "./ipc.types");

    expect(code).toContain(`["custom-api-root"]: IpcApi;`);
  });
});
