import type { ControllerMetadata, MethodMetadata } from "../parser/types.js";

import { generateRuntimeTypes } from "./generate-runtime-types.js";

describe("generateRuntimeTypes", () => {
  const makeController = (overrides: Partial<ControllerMetadata> = {}): ControllerMetadata => {
    return {
      className: "ExampleController",
      filePath: "/controllers/example.ts",
      methods: [],
      namespace: "example",
      referencedTypes: [],
      ...overrides,
    };
  };

  it("generates a header and IpcApi interface even when there are no controllers", () => {
    const output = generateRuntimeTypes([]);

    expect(output).toContain("// Auto-generated by @electron-ipc-controller/vite-plugin");
    expect(output).toContain("export interface IpcApi {");
  });

  it("includes type definitions and namespaces for controllers", () => {
    const methods: MethodMetadata[] = [
      {
        decoratorName: "IpcHandle",
        name: "bar",
        params: [],
        referencedTypes: [],
        returnType: "Promise<string>",
      },
    ];

    const controller = makeController({
      methods,
      namespace: "foo",
      referencedTypes: [
        {
          definition: "type Payload = { id: string }",
          name: "Payload",
          referencedTypes: [],
        },
      ],
    });

    const output = generateRuntimeTypes([controller]);

    expect(output).toContain("export type Payload = { id: string }");
    expect(output).toContain("export interface IpcApi {");
    expect(output).toContain("foo:");
    expect(output).toContain("bar(): Promise<string>;");
  });
});
