import { IPC_DEFAULT_API_ROOT } from "@electron-ipc-controller/shared";

export const generateGlobalTypes = (namespace: string = IPC_DEFAULT_API_ROOT, ipcApiImportPath: string): string => {
  const isValidIdentifier = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(namespace);
  const windowProperty = isValidIdentifier ? `${namespace}: IpcApi;` : `[${JSON.stringify(namespace)}]: IpcApi;`;

  return `// Auto-generated by @electron-ipc-controller/vite-plugin
// Do not edit manually

import type { IpcApi } from "${ipcApiImportPath}";

declare global {
  interface Window {
    ${windowProperty}
  }
}

export {};
`;
};
