import { ControllerMetadata } from "../parser/types.js";

import { getReturnType } from "./get-return-type.js";

export const generateTypes = (controllers: ControllerMetadata[]): string => {
  const namespaces = controllers.map((controller) => {
    const methods = controller.methods.map((method) => {
      const params = method.params.map((p) => `${p.name}${p.optional ? "?" : ""}: ${p.type}`).join(", ");
      const returnType = getReturnType(method.decoratorName, method.returnType);
      return `${method.name}(${params}): ${returnType};`;
    });

    return `    ${controller.namespace}: {\n      ${methods.join("\n      ")}\n    };`;
  });

  return `/* eslint-disable */
// Auto-generated by @electron-ipc-controller/vite-plugin
// Do not edit manually

export interface IpcApi {
${namespaces.join("\n")}
}

declare global {
  interface Window {
    ipc: IpcApi;
  }
}

export {};
`;
};
