import type { ControllerMetadata } from "../parser/types.js";

import { buildNamespaces } from "./build-namespaces.js";
import { buildTypeDefinitions } from "./build-type-definitions.js";

export const generateRuntimeTypes = (controllers: ControllerMetadata[]): string => {
  const typeDefinitions = buildTypeDefinitions(controllers);
  const namespaces = buildNamespaces(controllers);

  return `// Auto-generated by @electron-ipc-controller/vite-plugin
// Do not edit manually

${typeDefinitions}

export interface IpcApi {
${namespaces.join("\n")}
}
`;
};
