// Auto-generated by @electron-ipc-controller/vite-plugin
// Do not edit manually

import type { IpcApi } from '../renderer/src/ipc.types'

declare global {
  interface Window {
    ipc: IpcApi
  }
}

export {}
